---
- hosts: ec2-instances
  tasks:
   - name: reboot
     become: yes
     become_user: root
     command: shutdown -r now "Reboot triggered by Ansible"
     async: 0
     poll: 0
     ignore_errors: true
